# Github action to run test.py every week ona monday at 8 am GMT
name: Run dbgapmonitor

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  dbGap_to_slack:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run dbgapmonitor.py
      run: python dbgapmonitor.py